services:
  postgres:
    image: postgres:15
    container_name: instagram_db
    restart: always
    environment:
      POSTGRES_USER: insta_user
      POSTGRES_PASSWORD: insta_pass
      POSTGRES_DB: instagram
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
